### ISSUE TITLE
Generate a separate crossing node when generating the crossings

### ISSUE THREAD

**Issue by 3vivekb** [AccessMap/crossify#6]
Provide an option to generate crossing nodes where the crossing intersects with the road.  The node can just be a separate point.  

Thus in JOSM the user can select these nodes and have them join to the segment if they are acceptable.  They should have the tag ```highway=crossing```

This shouldn't be generated for a crossing if #5 is triggered.

**Comment by nbolten** [comment]
Heya! I recommend using the JOSM `utilsplugin2` plugin, which lets you add nodes to crossing ways using <kbd>Shift</kbd>+<kbd>I</kbd>, and other handy stuff. That will actually require fewer keystrokes / positioning than pre-adding a node.

With that said, I envision that we'll want a souped-up import workflow at some point that enables greater automation. For example, if OSM data were read in immediately prior to starting the import, and supplied with the download, that node could be pre-created and shared by the street in the uploaded data by default.

I'm going to close this for now, but feel free to open up a new issue related to on-the-fly data integration. It's technically out of scope for this project, but could serve as a starting point for an organizational repo.

**Comment by 3vivekb** [comment]
Yo!  I'm pretty familiar with utilsplugin2.  We use it for the sidewalks  I was trying it along with the intersections the other night.  Sadly it runs into an issue (maybe there is a way around it?)

If you pick a single intersection, using <kbd>i</kbd> to select the intersecting roads and then <kbd>Shift</kbd>+<kbd>i</kbd> works no problem, adds a crossing node.

But what I was trying to select all the intersections that were autogenerated, and then selecting all of their intersecting ways <kbd>i</kbd>.  Then when you hit <kbd>Shift</kbd>+<kbd>i</kbd>, it does add the intersections as expected.  Unfortunately it will also grab any power lines or areas that also intersect the roads  and ways selected and adds intersections to them as well.  Thus it would be superhelpful if the nodes were already there and I just joined them to the road + intersection.

I don't think filters helped.  Is there a way to not grab more than what we want?

**Comment by 3vivekb** [comment]
Hmm. Maybe if I use JOSM in expert mode using the overpass api I can get around this error.
